config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sitemap', to: 'application#sitemap'

  namespace :conveyancing_quotes, path: 'conveyancing-quotes' do
    concern :downloadable do
      resource :download, only: [:show]
    end

    resource :stamp_duty_calculator,
              only: :create,
              path: 'stamp-duty-calculator'

    resource :sales,
             only: :update

    resource :purchases,
             only: :update

    resource :sale_and_purchases,
             only: :create,
             path: 'sale-and-purchase'

    # resource :deeds,
    #         only: %i[new edit update]

    # resource :property_addresses,
    #         only: %i[new create edit update],
    #         path: 'property-address'

    # resource :correspondence_addresses,
    #         only: %i[new create edit update],
    #         path: 'correspondence-address'

    resource :callback_requests,
             only: %i[new create]

    resources :quote_locations,
              only: :show,
              path: '',
              shallow: true,
              as: :location do
      resource :users,
               only: %i[new create edit update show],
               path: 'request',
               concerns: :downloadable do
        get 'thank-you', on: :collection
      end
    end
  end

  resources :frequently_asked_questions, only: [:index], path: 'frequently-asked-questions'
  resources :payments, only: %i[new create show]
  match '/payments/gateway_reply', to: 'payment_gateway_replies#create', via: %i[get post]
  resources :testimonials, only: [:index]

  resources :team_members, only: %i[index show], path: 'team-members' do
    member do
      get 'testimonials'
    end
    collection do
      get 'search'
      resources :audiences, path: 'services', only: [] do
        resources :services, only: :show, path: '', controller: 'team_members/services', as: 'team_member_services'
      end
    end
  end

  resources :article_categories, only: :show, path: 'article-categories'
  resources :office_locations, only: :show, path: 'office-locations'
  resources :resource_categories, only: :show, path: 'resource-categories'
  # resources :video_categories, only: :show, path: 'video-categories'
  resources :event_categories, only: :show, path: 'event-categories'
  resources :event_locations, only: :show, path: 'event-locations'

  # resources :case_studies, only: %i[index show], path: 'case-studies'
  resources :articles, only: %i[index show]
  resources :offices, only: %i[index show]
  resources :resources, only: %i[index show]
  # resources :videos, only: [:index, :show]
  resources :events, only: %i[index show]
  resources :pages, only: :show
  # FIXME: This is used in conjuction with the engine, so you end up with
  # /contacts/new and /contact-us/new - it should be one or the other.
  resources :contacts, only: %i[new create] # Here for legacy
  resources :contacts, only: %i[new create], path: 'contact-us' do
    post 'inpage-contact', on: :collection, as: :inpage, to: 'contacts#inpage'
  end
  resources :callback_requests, only: %i[new create], path: 'callback-request'

  %w[403 404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => '/admin'

  root to: 'homes#show'

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/testimonials',
      to: 'services#testimonials',
      as: :audience_child_service_testimonials

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/frequently-asked-questions',
      to: 'services#frequently_asked_questions',
      as: :audience_child_service_frequently_asked_questions

  resources :audiences, only: :show, path: '', constraints: AudienceConstraint.new(Audience) do
    resources :services, only: :show do
      get 'testimonials'
      get 'frequently-asked-questions'

      resources :resources,
                only: :show,
                controller: 'services/resources'

      resources :service_pages,
                only: :show,
                path: 'pages',
                controller: 'services/pages'

      resources :services, only: :show, path: '', param: :nested_id do
        get 'testimonials'
        get 'frequently-asked-questions'

        resources :service_pages,
                  only: :show,
                  path: 'pages',
                  controller: 'services/pages'
      end
    end
  end

  resources :searches, only: :new

  get '/:audience_id/services/:parent_service_id/:service_id/:id',
      to: 'services#show',
      as: :audience_child_service

  get '/:audience_id/services/:grandparent_service_id/:parent_service_id/:service_id/pages/:id',
      to: 'services/pages#show',
      as: :audience_child_service_page

  # This has to be the last route in your list
  match '*path', to: 'errors#show', via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
Optimadmin::Engine.routes.draw do
  concern :imageable do
    member do
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  concern :orderable do
    collection do
      post 'order'
    end
  end

  concern :toggleable do
    member do
      get 'toggle'
    end
  end

  concern :publishable do |options|
    collection do
      resources :expired,
                as: "expired_#{options[:module]}",
                controller: "#{options[:module]}/expired"
      resources :scheduled,
                as: "scheduled_#{options[:module]}",
                controller: "#{options[:module]}/scheduled"
      resources :published,
                as: "published_#{options[:module]}",
                controller: "#{options[:module]}/published"
    end
  end

  # Module routes go below concerns

  get :resource_details, to: 'resources#details'
  resources :office_locations, concerns: %i[toggleable imageable]

  resources :resources do
    resources :resources_sections,
    except: :show,
    concerns: %i[orderable toggleable imageable],
    path: 'sections',
    controller: 'resources/sections'
  end

  namespace :conveyancing_quotes do
    resources :configurations,
              except: :show,
              concerns: %i[orderable toggleable imageable]
    resources :quote_locations do
      resources :users, only: %i[index show] do
        get 'incomplete', on: :collection
      end
    end
  end
end

app/models/concerns/extensions/callback_request.rb
module Extensions
  module CallbackRequest
    extend ActiveSupport::Concern

    included do
      attr_accessor :forename, :surname, :email_address, :contact_telephone,
                    :callback_time, :preferred_office, :service, :enquiry_type,
                    :how_heard, :wealth_management, :from_url, :mediation,
                    :large_modal

      validates :forename, :surname, :contact_telephone,
                :callback_time, :enquiry_type, presence: true

      TIMES = %w(Morning Afternoon Anytime).freeze
    end

    class_methods do
    end
  end
end

app/models/conveyancing_quotes/callback_request.rb
module ConveyancingQuotes
  class CallbackRequest
    include ActiveModel::Model

    attr_accessor :forename,
                  :surname,
                  :email_address,
                  :contact_telephone,
                  :purchase_price,
                  :purchase_freehold_house,
                  :purchase_freehold_apartment,
                  :purchase_leasehold_house,
                  :purchase_leasehold_apartment,
                  :sale_price,
                  :sale_freehold_house,
                  :sale_freehold_apartment,
                  :sale_leasehold_house,
                  :sale_leasehold_apartment

    validates :forename, presence: true
    validates :surname, presence: true
    validates :email_address, presence: true
    validates :contact_telephone, presence: true

    validates :purchase_price, presence: { message: 'can not be blank, unless sale price is present' }, if: proc { |x| x.sale_price.blank? }
    validates :sale_price, presence: { message: 'can not be blank, unless purchase price is present' }, if: proc { |x| x.purchase_price.blank? }
  end
end

app/controllers/callback_requests_controller.rb
class CallbackRequestsController < ApplicationController
  before_action :load_modules

  def new
    @callback_request = CallbackRequest.new
  end

  def create
    @callback_request = CallbackRequest.new(callback_request_params)
    process_callback_request(@callback_request)
  end

  private

  def process_callback_request(callback_request)
    if callback_request.valid?
      CallbackRequestMailer.new_callback_request(callback_request).deliver_now
      record_form_submission(callback_request)
    end
    respond_to do |format|
      format.html { html_callback_request(callback_request) }
      format.js { js_callback_request(callback_request) }
    end
  end

  def html_callback_request(callback_request)
    if callback_request.valid?
      redirect_to new_callback_request_path, notice: 'Thank you for your submission.'
    else
      render :new
    end
  end

  def js_callback_request(callback_request)
    flash.notice = 'Thank you for contacting us' if callback_request.valid?
  end

  def callback_request_params
    params.require(:callback_request)
          .permit!
  end

  def load_modules
    @offices = Office.displayed if Flipflop.offices?
  end
end

app/controllers/conveyancing_quotes/callback_requests_controller.rb
module ConveyancingQuotes
  class CallbackRequestsController < ApplicationController
    def new
      @callback_request = ConveyancingQuotes::CallbackRequest.new
    end

    def create
      @callback_request = ConveyancingQuotes::CallbackRequest.new(callback_request_params)
      process_callback_request(@callback_request)
    end

    private

    def process_callback_request(callback_request)
      ConveyancingQuoteMailer.new_callback_request(callback_request).deliver_now if callback_request.valid?
      respond_to do |format|
        format.html { html_callback_request(callback_request) }
        format.js { js_callback_request(callback_request) }
      end
    end

    def html_callback_request(callback_request)
      if callback_request.valid?
        redirect_to new_callback_request_path, notice: 'Thank you for your submission.'
      else
        render :new
      end
    end

    def js_callback_request(callback_request)
     flash.notice = 'Thank you for contacting us' if callback_request.valid?
    end

    def callback_request_params
      params.require(:conveyancing_quotes_callback_request)
            .permit!
    end
  end
end

app/views/callback_requests/shared/_form_fields_solicitors.html.erb
<div class="contact-details">
  <div class="field">
    <%= f.label :forename %>
    <%= f.text_field :forename %>
  </div>
  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :contact_telephone %>
    <%= f.text_field :contact_telephone %>
  </div>
  <div class="field">
    <%= f.label :callback_time %>
    <%= f.select :callback_time, options_for_select(CallbackRequest::TIMES) %>
  </div>

  <% if @offices.present? %>
    <div class="field">
      <%= f.label :preferred_office %>
      <%= f.select :preferred_office, options_for_select(@offices.map{|x| x.address_fields }), prompt: 'Please select' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enquiry_type %>
    <%= f.text_area :enquiry_type %>
  </div>
  <% if Flipflop.services? %>
    <div class="field">
      <%= f.label :service %>
      <%= f.select :service, grouped_options_for_select(@form_audiences), prompt: 'Please select' %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :how_heard, 'How did you find us?' %>
    <%= f.select :how_heard, options_for_select(Contact::HOW_HEARDS), include_blank: 'Please select' %>
  </div>

  <%= f.hidden_field :from_url, value: request.original_url %>

  <div class="actions">
    <%= f.submit "Send", class: "submit-button" %>
  </div>
</div>

app/views/callback_requests/shared/_large_modal.html.erb
<%= render 'shared/flash_messages' %>

<%= form_for @callback_request, url: callback_requests_path, remote: true, html: { class: 'large-modal-remote-callback-request-form' } do |f| %>
  <% if @callback_request.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize @callback_request.errors.count, 'error' %> prevented this message from being sent
      </h2>
      <ul>
        <% @callback_request.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <% if (@page.present? && @page.layout == 'wealth_management') || @callback_request.wealth_management.present? %>
    <%= render partial: 'callback_requests/shared/remote_form_fields_wealth_management', locals: { f: f }  %>
  <% elsif (@service.present? && @service.title == 'Mediation') || @callback_request.mediation.present? %>
    <%= render partial: 'callback_requests/shared/large_modal/fields_solicitors', locals: { f: f, mediation: true }  %>
  <% else %>
    <%= render partial: 'callback_requests/shared/large_modal/fields_solicitors', locals: { f: f }  %>
  <% end %>
<% end %>

app/views/callback_requests/shared/_remote_form_fields_solicitors.html.erb
<div class="contact-details">
  <div class="related-fields">
    <div class="field">
      <%= f.label :forename %>
      <%= f.text_field :forename, placeholder: "Forename" %>
    </div>
    <div class="field">
      <%= f.label :surname %>
      <%= f.text_field :surname, placeholder: "Surname" %>
    </div>
  </div>

  <div class="related-fields">
    <div class="field">
      <%= f.label :email_address %>
      <%= f.text_field :email_address, placeholder: "Email Address" %>
    </div>
    <div class="field">
      <%= f.label :contact_telephone %>
      <%= f.text_field :contact_telephone, placeholder: "Contact Phone" %>
    </div>
  </div>

  <% if @offices.present? %>
    <div class="related-fields">
  <% end %>
    <div class="field">
      <%= f.label :callback_time %>
      <%= f.select :callback_time, options_for_select(CallbackRequest::TIMES), prompt: 'Callback time' %>
    </div>
    <% if @offices.present? %>
      <div class="field">
        <%= f.label :preferred_office %>
        <%= f.select :preferred_office, options_for_select(@offices.map{|x| x.address_fields }), prompt: 'Preferred office' %>
      </div>
    <% end %>
  <% if @offices.present? %>
    </div>
  <% end %>

  <div class="related-fields">
    <% if Flipflop.services? %>
      <div class="field">
        <%= f.label :service %>
        <%= f.select :service, grouped_options_for_select(@form_audiences), prompt: 'Service' %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :how_heard, 'How did you find us?' %>
      <%= f.select :how_heard, options_for_select(['Google search', 'Yell.com search', 'Other search', 'Advertisement', 'Facebook advert', 'Recommendation', 'Existing client', 'Peak FM advert', 'TV advert']), include_blank: 'How did you find us?' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :enquiry_type %>
    <%= f.text_area :enquiry_type, placeholder: "Enquiry" %>
  </div>

  <%= f.hidden_field :mediation, value: 1 if defined?(mediation) %>
  <%= f.hidden_field :from_url, value: request.original_url %>

  <div class="actions">
    <%= f.submit "Send", class: "submit-button" %>
  </div>
</div>

app/views/callback_requests/shared/_remote_form_fields_wealth_management.html.erb
<div class="contact-details">
  <div class="related-fields">
    <div class="field">
      <%= f.label :forename %>
      <%= f.text_field :forename, placeholder: "Forename" %>
    </div>
    <div class="field">
      <%= f.label :surname %>
      <%= f.text_field :surname, placeholder: "Surname" %>
    </div>
  </div>

  <div class="related-fields">
    <div class="field">
      <%= f.label :email_address %>
      <%= f.text_field :email_address, placeholder: "Email Address" %>
    </div>
    <div class="field">
      <%= f.label :contact_telephone %>
      <%= f.text_field :contact_telephone, placeholder: "Contact Phone" %>
    </div>
  </div>

  <div class="related-fields">
    <div class="field">
      <%= f.label :callback_time %>
      <%= f.select :callback_time, options_for_select(CallbackRequest::TIMES), prompt: 'Callback time' %>
    </div>
    <div class="field">
      <%= f.label :how_heard %>
      <%= f.select :how_heard, options_for_select(Contact::HOW_HEARDS), include_blank: 'How did you find us?' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :enquiry_type %>
    <%= f.text_area :enquiry_type, placeholder: "Enquiry" %>
  </div>

  <%= f.hidden_field :wealth_management, value: '1' %>
  <%= f.hidden_field :from_url, value: request.original_url %>

  <div class="actions">
    <%= f.submit "Send", class: "submit-button" %>
  </div>
</div>