config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sitemap', to: 'application#sitemap'

  namespace :conveyancing_quotes, path: 'conveyancing-quotes' do
    concern :downloadable do
      resource :download, only: [:show]
    end

    resource :stamp_duty_calculator,
              only: :create,
              path: 'stamp-duty-calculator'

    resource :sales,
             only: :update

    resource :purchases,
             only: :update

    resource :sale_and_purchases,
             only: :create,
             path: 'sale-and-purchase'

    # resource :deeds,
    #         only: %i[new edit update]

    # resource :property_addresses,
    #         only: %i[new create edit update],
    #         path: 'property-address'

    # resource :correspondence_addresses,
    #         only: %i[new create edit update],
    #         path: 'correspondence-address'

    resource :callback_requests,
             only: %i[new create]

    resources :quote_locations,
              only: :show,
              path: '',
              shallow: true,
              as: :location do
      resource :users,
               only: %i[new create edit update show],
               path: 'request',
               concerns: :downloadable do
        get 'thank-you', on: :collection
      end
    end
  end

  resources :frequently_asked_questions, only: [:index], path: 'frequently-asked-questions'
  resources :payments, only: %i[new create show]
  match '/payments/gateway_reply', to: 'payment_gateway_replies#create', via: %i[get post]
  resources :testimonials, only: [:index]

  resources :team_members, only: %i[index show], path: 'team-members' do
    member do
      get 'testimonials'
    end
    collection do
      get 'search'
      resources :audiences, path: 'services', only: [] do
        resources :services, only: :show, path: '', controller: 'team_members/services', as: 'team_member_services'
      end
    end
  end

  resources :article_categories, only: :show, path: 'article-categories'
  resources :office_locations, only: :show, path: 'office-locations'
  resources :resource_categories, only: :show, path: 'resource-categories'
  # resources :video_categories, only: :show, path: 'video-categories'
  resources :event_categories, only: :show, path: 'event-categories'
  resources :event_locations, only: :show, path: 'event-locations'

  # resources :case_studies, only: %i[index show], path: 'case-studies'
  resources :articles, only: %i[index show]
  resources :offices, only: %i[index show]
  resources :resources, only: %i[index show]
  # resources :videos, only: [:index, :show]
  resources :events, only: %i[index show]
  resources :pages, only: :show
  # FIXME: This is used in conjuction with the engine, so you end up with
  # /contacts/new and /contact-us/new - it should be one or the other.
  resources :contacts, only: %i[new create] # Here for legacy
  resources :contacts, only: %i[new create], path: 'contact-us' do
    post 'inpage-contact', on: :collection, as: :inpage, to: 'contacts#inpage'
  end
  resources :callback_requests, only: %i[new create], path: 'callback-request'

  %w[403 404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => '/admin'

  root to: 'homes#show'

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/testimonials',
      to: 'services#testimonials',
      as: :audience_child_service_testimonials

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/frequently-asked-questions',
      to: 'services#frequently_asked_questions',
      as: :audience_child_service_frequently_asked_questions

  resources :audiences, only: :show, path: '', constraints: AudienceConstraint.new(Audience) do
    resources :services, only: :show do
      get 'testimonials'
      get 'frequently-asked-questions'

      resources :resources,
                only: :show,
                controller: 'services/resources'

      resources :service_pages,
                only: :show,
                path: 'pages',
                controller: 'services/pages'

      resources :services, only: :show, path: '', param: :nested_id do
        get 'testimonials'
        get 'frequently-asked-questions'

        resources :service_pages,
                  only: :show,
                  path: 'pages',
                  controller: 'services/pages'
      end
    end
  end

  resources :searches, only: :new

  get '/:audience_id/services/:parent_service_id/:service_id/:id',
      to: 'services#show',
      as: :audience_child_service

  get '/:audience_id/services/:grandparent_service_id/:parent_service_id/:service_id/pages/:id',
      to: 'services/pages#show',
      as: :audience_child_service_page

  # This has to be the last route in your list
  match '*path', to: 'errors#show', via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
Optimadmin::Engine.routes.draw do
  concern :imageable do
    member do
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  concern :orderable do
    collection do
      post 'order'
    end
  end

  concern :toggleable do
    member do
      get 'toggle'
    end
  end

  concern :publishable do |options|
    collection do
      resources :expired,
                as: "expired_#{options[:module]}",
                controller: "#{options[:module]}/expired"
      resources :scheduled,
                as: "scheduled_#{options[:module]}",
                controller: "#{options[:module]}/scheduled"
      resources :published,
                as: "published_#{options[:module]}",
                controller: "#{options[:module]}/published"
    end
  end

  # Module routes go below concerns

  get :resource_details, to: 'resources#details'
  resources :office_locations, concerns: %i[toggleable imageable]

  resources :resources do
    resources :resources_sections,
    except: :show,
    concerns: %i[orderable toggleable imageable],
    path: 'sections',
    controller: 'resources/sections'
  end

  namespace :conveyancing_quotes do
    resources :configurations,
              except: :show,
              concerns: %i[orderable toggleable imageable]
    resources :quote_locations do
      resources :users, only: %i[index show] do
        get 'incomplete', on: :collection
      end
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def index
    @offices = displayed_offices
  end

  def show
    @office = find_office
    @offices = displayed_offices
    friendly_id_redirect(@office)
  end

  private

  def displayed_offices
    Office.displayed
  end

  def find_office
    Office.displayed.find(params[:id])
  end
end

app/controllers/optimadmin/offices_controller.rb
module Optimadmin
  class OfficesController < Optimadmin::ApplicationController
    before_action :feature_check

    before_action :set_office, only: [:show, :edit, :update, :destroy]
    before_action :display_status, only: :index

    include Optimadmin::OfficeCrops

    def index
      @pagination_helper = @all_items
                           .pagination(params[:page], params[:per_page])

      @offices = Optimadmin::BaseCollectionPresenter.new(
        collection: @pagination_helper,
        view_template: view_context,
        presenter: Optimadmin::OfficePresenter
      )
    end

    def show
    end

    def new
      @office = Office.new
    end

    def edit
    end

    def create
      @office = Office.new(office_params)
      if @office.save
        redirect_to_index_or_continue_editing(@office)
      else
        render :new
      end
    end

    def update
      if @office.update(office_params)
        redirect_to_index_or_continue_editing(@office)
      else
        render :edit
      end
    end

    def destroy
      @office.destroy
      redirect_to offices_url, notice: 'Office was successfully destroyed.'
    end

    private

    def display_status
      @all_items = Office.field_order(params[:order])
                         .field_search(params[:search], 'building_name')
      @scheduled_items = @all_items.scheduled
      @published_items = @all_items.published
      @expired_items   = @all_items.expired
    end

    def set_office
      @office = Office.friendly.find(params[:id])
    end

    def office_params
      params.require(:office).permit(:building_name, :address_line_1, :address_line_2,
                                     :office_location_id, :postcode, :phone_number, :fax_number, :email,
                                     :dx_number, :details, :image, :publish_at, :expire_at,
                                     :remote_image_url, :remove_image, :image_cache, :page_title,
                                     :latitude, :longitude,
                                     :suggested_url, service_ids: [], team_member_ids: [])
    end

    def feature_check
      return redirect_to root_url unless Flipflop.offices?
    end
  end
end

app/views/offices/_office.html.erb
<% cache [office, office.office_location, office_counter] do %>
  <div class="office office-<%= office_counter %>">
    <div class="standard-content-box">
      <% present office.office_location do |office_location_presenter| %>
        <div class="index-office-location-name">
          <%= office.office_location_name %>
        </div>
      <% end %>

      <% present office do |office_presenter| %>
        <div class="index-office-address-fields">
          <%= raw office_presenter.address_fields.gsub(', ', '<br />') %>
        </div>

        <div class="index-office-buttons">
          <%= office_presenter.linked_text('View map', { title: office.address_fields, class: 'index-office-button' } ) %>

          <%= render partial: 'offices/shared/directions', locals: { office: office, office_presenter: office_presenter } %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/offices/_team_member_office.html.erb
<% cache [team_member, office.office_location, office] do %>
  <%= link_to "#{office.office_location_name}#{" - #{office.building_name}" if office.building_name.present?}", office_path(office) %><%= ', ' unless office == team_member.offices.last %>
<% end %>

app/views/offices/index.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag 'components/offices/map' %>
  <script>
  function equalHeightOffices() {
    $('.office').matchHeight({
      byRow: false
    });
  }

  $(document).ready(function() {
    equalHeightOffices();
  });

  $(document).on('click', '.toggle-class', function() {
    equalHeightOffices();
  });
  </script>
<% end %>



<div class="large-content">
  <aside class="large-content__aside">
    <div class="large-content-aside-sticky">
      <div class="large-content-aside-title">
        <h2 class="large-content-aside-title__text">
          Our Offices
        </h2>
      </div>

      <ul class="large-content-aside-navigation large-content-aside-navigation--without-icon" id="large-content-aside-navigation">
        <%= render partial: 'offices/shared/aside_navigation',
                   collection: @offices,
                   as: :office,
                   cached: true %>
      </ul>
    </div>
  </aside>

  <main class="large-content__main large-content__main--no-padding">
    <div class="offices-index-map" id="map-canvas" data-locations="<%= @offices.to_json %>">
      <%= image_tag 'components/icons/loading.gif', alt: 'Loading...' %>
    </div>

    <section class="large-content-element">
      <div class="large-content-element__container">
        <div class="large-content-inner">
          <div class="large-content-inner__main large-content-inner__main--full">
            <div class="large-content-offices-index">
              <%= render partial: 'offices/office', collection: @offices, as: :office, cached: true %>
            </div>
          </div>

          <aside class="large-content-inner__aside">

          </aside>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/offices/show.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag 'components/offices/map' %>
  <script>
    function equalHeightOffices() {
      $('.office').matchHeight({
        byRow: false
      });
    }

    $(document).ready(function() {
      equalHeightOffices();
    });

    $(document).on('click', '.toggle-class', function() {
      equalHeightOffices();
    });
  </script>
<% end %>
<div class="large-content">
  <aside class="large-content__aside">
    <div class="large-content-aside-sticky">
      <div class="large-content-aside-title">
        <h2 class="large-content-aside-title__text">
          Our Offices
        </h2>
      </div>
      <ul class="large-content-aside-navigation large-content-aside-navigation--without-icon" id="large-content-aside-navigation">
        <%= render partial: 'offices/shared/aside_navigation',
                   collection: @offices,
                   as: :office,
                   cached: true %>
      </ul>
    </div>
  </aside>
  <main class="large-content__main large-content__main--no-padding">
    <div class="offices-index-map" id="map-canvas" data-locations="<%= @offices.to_json %>">
      <%= image_tag 'components/icons/loading.gif', alt: 'Loading...' %>
    </div>
    <% cache [@office, @office.services.map(&:updated_at).max] do %>
      <section class="large-content-element">
        <div class="large-content-element__container">
          <div class="large-content-inner">
            <section class="office-location-content">
              <div class="content-section content-section--shadow">
                <div class="content-section__full">
                  <h1 class="standard-content-box-title standard-content-box-title--no-border">
                    <%= @office.office_location_name %>
                  </h1>
                  <%= raw @office.details %>
                </div>
              </div>
            </section>
            <aside class="office-location-aside">
              <div class="content-section content-section--shadow">
                <div class="content-section__full">
                  <%= render 'offices/shared/aside',
                            office: @office,
                            office_counter: 0,
                            aside: true %>
                </div>
              </div>
                <% @office.services.roots.group_by(&:audience).each do |audience, services| %>
                  <div class="content-section content-section--shadow">
                    <div class="content-section__full">
                      <h2 class="page-aside-navigation-title">
                        <%= link_to audience.title, audience %>
                      </h2>
                      <div class="page-aside-navigation-links">
                        <ul class="page-aside-navigation-links-list">
                          <%= render partial: 'offices/shared/service',
                                        collection: services,
                                        as: :service,
                                        cached: true %>
                        </ul>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </section>
    <% end %>
</main>
</div>