config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sitemap', to: 'application#sitemap'

  namespace :conveyancing_quotes, path: 'conveyancing-quotes' do
    concern :downloadable do
      resource :download, only: [:show]
    end

    resource :stamp_duty_calculator,
              only: :create,
              path: 'stamp-duty-calculator'

    resource :sales,
             only: :update

    resource :purchases,
             only: :update

    resource :sale_and_purchases,
             only: :create,
             path: 'sale-and-purchase'

    # resource :deeds,
    #         only: %i[new edit update]

    # resource :property_addresses,
    #         only: %i[new create edit update],
    #         path: 'property-address'

    # resource :correspondence_addresses,
    #         only: %i[new create edit update],
    #         path: 'correspondence-address'

    resource :callback_requests,
             only: %i[new create]

    resources :quote_locations,
              only: :show,
              path: '',
              shallow: true,
              as: :location do
      resource :users,
               only: %i[new create edit update show],
               path: 'request',
               concerns: :downloadable do
        get 'thank-you', on: :collection
      end
    end
  end

  resources :frequently_asked_questions, only: [:index], path: 'frequently-asked-questions'
  resources :payments, only: %i[new create show]
  match '/payments/gateway_reply', to: 'payment_gateway_replies#create', via: %i[get post]
  resources :testimonials, only: [:index]

  resources :team_members, only: %i[index show], path: 'team-members' do
    member do
      get 'testimonials'
    end
    collection do
      get 'search'
      resources :audiences, path: 'services', only: [] do
        resources :services, only: :show, path: '', controller: 'team_members/services', as: 'team_member_services'
      end
    end
  end

  resources :article_categories, only: :show, path: 'article-categories'
  resources :office_locations, only: :show, path: 'office-locations'
  resources :resource_categories, only: :show, path: 'resource-categories'
  # resources :video_categories, only: :show, path: 'video-categories'
  resources :event_categories, only: :show, path: 'event-categories'
  resources :event_locations, only: :show, path: 'event-locations'

  # resources :case_studies, only: %i[index show], path: 'case-studies'
  resources :articles, only: %i[index show]
  resources :offices, only: %i[index show]
  resources :resources, only: %i[index show]
  # resources :videos, only: [:index, :show]
  resources :events, only: %i[index show]
  resources :pages, only: :show
  # FIXME: This is used in conjuction with the engine, so you end up with
  # /contacts/new and /contact-us/new - it should be one or the other.
  resources :contacts, only: %i[new create] # Here for legacy
  resources :contacts, only: %i[new create], path: 'contact-us' do
    post 'inpage-contact', on: :collection, as: :inpage, to: 'contacts#inpage'
  end
  resources :callback_requests, only: %i[new create], path: 'callback-request'

  %w[403 404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => '/admin'

  root to: 'homes#show'

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/testimonials',
      to: 'services#testimonials',
      as: :audience_child_service_testimonials

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/frequently-asked-questions',
      to: 'services#frequently_asked_questions',
      as: :audience_child_service_frequently_asked_questions

  resources :audiences, only: :show, path: '', constraints: AudienceConstraint.new(Audience) do
    resources :services, only: :show do
      get 'testimonials'
      get 'frequently-asked-questions'

      resources :resources,
                only: :show,
                controller: 'services/resources'

      resources :service_pages,
                only: :show,
                path: 'pages',
                controller: 'services/pages'

      resources :services, only: :show, path: '', param: :nested_id do
        get 'testimonials'
        get 'frequently-asked-questions'

        resources :service_pages,
                  only: :show,
                  path: 'pages',
                  controller: 'services/pages'
      end
    end
  end

  resources :searches, only: :new

  get '/:audience_id/services/:parent_service_id/:service_id/:id',
      to: 'services#show',
      as: :audience_child_service

  get '/:audience_id/services/:grandparent_service_id/:parent_service_id/:service_id/pages/:id',
      to: 'services/pages#show',
      as: :audience_child_service_page

  # This has to be the last route in your list
  match '*path', to: 'errors#show', via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
Optimadmin::Engine.routes.draw do
  concern :imageable do
    member do
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  concern :orderable do
    collection do
      post 'order'
    end
  end

  concern :toggleable do
    member do
      get 'toggle'
    end
  end

  concern :publishable do |options|
    collection do
      resources :expired,
                as: "expired_#{options[:module]}",
                controller: "#{options[:module]}/expired"
      resources :scheduled,
                as: "scheduled_#{options[:module]}",
                controller: "#{options[:module]}/scheduled"
      resources :published,
                as: "published_#{options[:module]}",
                controller: "#{options[:module]}/published"
    end
  end

  # Module routes go below concerns

  get :resource_details, to: 'resources#details'
  resources :office_locations, concerns: %i[toggleable imageable]

  resources :resources do
    resources :resources_sections,
    except: :show,
    concerns: %i[orderable toggleable imageable],
    path: 'sections',
    controller: 'resources/sections'
  end

  namespace :conveyancing_quotes do
    resources :configurations,
              except: :show,
              concerns: %i[orderable toggleable imageable]
    resources :quote_locations do
      resources :users, only: %i[index show] do
        get 'incomplete', on: :collection
      end
    end
  end
end

app/models/team_members.rb
module TeamMembers
  def self.table_name_prefix
    'team_members_'
  end
end

app/controllers/team_members/services_controller.rb
module TeamMembers
  class ServicesController < ApplicationController
    before_action :find_member_service

    include ResourceHelper, TwitterHelper

    def show
      return redirect_to audience_team_member_service_path(@audience, @service), status: :moved_permanently if request.path != audience_team_member_service_path(@audience, @service)
      @team_members = @service.team_members.displayed
      @current_service = @service
      render 'team_members/index'
    end

    private

    def find_member_service
      @audience = Audience.displayed.friendly.find(params[:audience_id])
      @service = @audience.services.displayed.friendly.find(params[:id])
    end
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_search_service, only: :search
  before_action :load_form_field_objects
  before_action :find_team_member, only: [:testimonials]

  def index
    @office = Office.displayed.find(params[:office_id]) if params[:office_id].present?
    @team_members = @office.present? ? @office.team_members.unscoped.displayed.order(:surname) : TeamMember.unscoped.displayed.order(:surname)
  end

  def show
    find_team_member
  end

  def search
    @team_members = if @service.blank?
                      TeamMember.displayed.filter(search_params.slice(:name_search, :office_id))
                    else
                      @service.team_members.displayed.filter(search_params.slice(:name_search, :office_id))
                    end

    respond_to do |format|
      format.js
      format.html { render 'team_members/index' }
    end
  end

  private

  def load_form_field_objects
    @offices = Office.unscoped.displayed.joins(:office_location).order('office_locations.name ASC')
    @services = Service.root_services.displayed.pluck(:title, :id)
  end

  def set_search_service
    @service = Service.displayed.find(params[:service_id]) if params[:service_id].present?
  end

  def search_params
    params.permit([:name_search, :office_id])
  end

  def find_team_member
    @team_member = TeamMember.displayed.find(params[:id])
    root_services = Service.joins(:service_team_members).where(services_team_members: { team_member_id: @team_member.id }).pluck(:id)
    @team_members = TeamMember.joins(:service_team_members).where(services_team_members: { service_id: root_services }).where.not(id: @team_member.id).limit(6)
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_team_member.html.erb
<% cache [team_member, team_member.job_roles.map(&:updated_at).max, team_member.department_roles.map(&:updated_at).max] do %>
  <% present team_member do |team_member_presenter| %>
    <div class="team-member">
      <div class="team-member-full-name">
        <%= team_member_presenter.full_name %>
      </div>

      <div class="team-member-role">
        <%= render(
          partial: "team_members/shared/profile_role",
          locals: {
            team_member: team_member,
            team_member_presenter: team_member_presenter
          }
        ) %>
    </div>

    <div class="team-member-primary-telephone">
      <%= team_member_presenter.primary_telephone %>
    </div>

    <div class="team-member-email-address">
      <%= team_member_presenter.linked_email_address %>
    </div>

    <% if team_member_presenter.dx_number.present? %>
      <div class="team-member-dx-number">
        <%= team_member_presenter.dx_number %>
      </div>
    <% end %>

    <% if team_member_presenter.mobile_number.present? %>
      <div class="team-member-mobile-number">
        <%= team_member_presenter.mobile_number %>
      </div>
    <% end %>

    <% if team_member_presenter.vcard.present? %>
      <div class="team-member-vcard">
        <%= team_member_presenter.vcard %>
      </div>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/team_members/index.html.erb
<%= content_for :javascript do %>
  <script>
    $(document).on('keyup', '.slider-team-member-search-name', function() {
      $(this).closest('form').submit();
      $('.slider-team-members-loading').css('display', 'block');
    });

    $(document).on('change', '.slider-team-member-search-select', function() {
      $(this).closest('form').submit();
      $('.slider-team-members-loading').css('display', 'block');
    });

    // http://craftedpixelz.co.uk/blog/conditional-js-with-modernizr-mq/
    if (Modernizr.mq('only screen and (min-width: 1200px)')) {
      var offsetHeight, $header, $moduleContent;

      function setFixedHeader() {
        if($(document).scrollTop() > offsetHeight) {
          $header.addClass('fixed');
          $moduleContent.css('padding-top', parseInt($header.height()));
        } else {
          $header.removeClass('fixed');
          $moduleContent.removeAttr('style');
        }
      }

      $(window).load(function() {
        $header = $('.index-fixed-team-members-search');
        $moduleContent = $('.team-members-index-wrap');
        offsetHeight = parseInt($('.primary-navigation-wrap').height()) + parseInt($('.primary-header').height());
        setFixedHeader();
      });

      $(window).scroll(function() {
        setFixedHeader();
      });
    }
  </script>
  <%= javascript_include_tag 'components/team-members/index-profile-card.js' %>
<% end %>


<div class="module-inner-content">
  <%= render 'team_members/shared/index_header', index: true %>

  <div class="team-members-index-wrap">
    <%= image_tag 'components/icons/loading.gif', alt: 'Loading...', class: 'slider-team-members-loading' %>

    <div class="team-members-index-content">
      <%= render partial: 'team_members/shared/index_profile_card', collection: @team_members, as: :team_member, cached: true %>
    </div>
  </div>
</div>


app/views/team_members/search.js.erb

<% if params[:index].blank? %>
  $('.slider-team-members-slick').slick('unslick');
  $('.slider-team-members-slick').html("<%= j render partial: 'team_members/shared/slider_team_member', collection: @team_members, as: :team_member if @team_members.present? %>");

  if($('.slider-team-member').length === 0) {
    $('.slider-team-member-profile-information').text('');
    $('.slider-team-member-profile-service-name').text('');
  }

  teamMembersSlick(12);
<% else %>
  $('.team-members-index-wrap').css('min-height', $('.team-members-index-wrap').height());
  $('.team-members-index-content')
    .html('<%= j render partial: 'team_members/shared/index_profile_card', collection: @team_members, as: :team_member if @team_members.present? %>')
    .promise()
    .done(function(){
      setTimeout(function() {
        $('.team-members-index-wrap').css('min-height', 'auto');
      }, 150);
    });
<% end %>

$('.slider-team-members-loading').removeAttr('style');
teamMemberEqualHeightProfileCard();

app/views/team_members/show.html.erb
<%= content_for :javascript do %>
  <script>
    $(document).ready(function() {
      if (Modernizr.mq('only screen and (min-width: 1024px)')) {
        $('.team-members-content-wrap, .team-member-show-text-profile').matchHeight();
      }
    });
  </script>
  <%= javascript_include_tag 'components/testimonials/slider.js' %>
  <%= javascript_include_tag 'components/team-members/index-profile-card.js' %>
<% end %>


<div class="module-inner-content">
  <%= render 'team_members/shared/index_header' %>
  <%= render 'team_members/shared/show_summary' %>

  <div class="team-members-content-wrap">
    <div class="page-content">
      <div class="standard-content-box">
        <% present @team_member do |team_member_presenter| %>
          <%= team_member_presenter.specialisms %>
          <%= render partial: 'accreditations/shared/team_member_accreditations', collection: @team_member.accreditations, as: :accreditation, cached: true %>
        <% end %>
      </div>
    </div>

    <% if @team_member.testimonials.present? %>
      <div class="page-content">
        <div class="onpage-navigation-item home-content-box inner testimonials">
          <%= link_to "See All", testimonials_team_member_path(@team_member), class: "see-all" if @team_member.testimonials.displayed.size > 6 %>

          <h2 class="home-content-box-title testimonials-title">
            Testimonials
          </h2>

          <div class="testimonials-slick">
            <%= render(
              partial: "testimonials/testimonial",
              collection: @team_member.testimonials.displayed.limit(6),
              cached: true,
              as: :testimonial
              )
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= render 'team_members/shared/show_footer' if @team_members.present? %>
</div>

app/views/team_members/testimonials.html.erb
<%= render 'testimonials/shared/javascript' %>

<div class="module-inner-content">
  <%= render 'team_members/shared/index_header' %>
  <%= render 'team_members/shared/show_summary' %>

  <div class="team-members-content-wrap">
    <div class="testimonials-list-wrap">
      <%= render partial: 'testimonials/shared/single_content_box', collection: @team_member.testimonials.displayed.limit(20), as: :testimonial, cached: true %>
    </div>
  </div>

  <%= render 'team_members/shared/show_footer' %>
</div>