config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sitemap', to: 'application#sitemap'

  namespace :conveyancing_quotes, path: 'conveyancing-quotes' do
    concern :downloadable do
      resource :download, only: [:show]
    end

    resource :stamp_duty_calculator,
              only: :create,
              path: 'stamp-duty-calculator'

    resource :sales,
             only: :update

    resource :purchases,
             only: :update

    resource :sale_and_purchases,
             only: :create,
             path: 'sale-and-purchase'

    # resource :deeds,
    #         only: %i[new edit update]

    # resource :property_addresses,
    #         only: %i[new create edit update],
    #         path: 'property-address'

    # resource :correspondence_addresses,
    #         only: %i[new create edit update],
    #         path: 'correspondence-address'

    resource :callback_requests,
             only: %i[new create]

    resources :quote_locations,
              only: :show,
              path: '',
              shallow: true,
              as: :location do
      resource :users,
               only: %i[new create edit update show],
               path: 'request',
               concerns: :downloadable do
        get 'thank-you', on: :collection
      end
    end
  end

  resources :frequently_asked_questions, only: [:index], path: 'frequently-asked-questions'
  resources :payments, only: %i[new create show]
  match '/payments/gateway_reply', to: 'payment_gateway_replies#create', via: %i[get post]
  resources :testimonials, only: [:index]

  resources :team_members, only: %i[index show], path: 'team-members' do
    member do
      get 'testimonials'
    end
    collection do
      get 'search'
      resources :audiences, path: 'services', only: [] do
        resources :services, only: :show, path: '', controller: 'team_members/services', as: 'team_member_services'
      end
    end
  end

  resources :article_categories, only: :show, path: 'article-categories'
  resources :office_locations, only: :show, path: 'office-locations'
  resources :resource_categories, only: :show, path: 'resource-categories'
  # resources :video_categories, only: :show, path: 'video-categories'
  resources :event_categories, only: :show, path: 'event-categories'
  resources :event_locations, only: :show, path: 'event-locations'

  # resources :case_studies, only: %i[index show], path: 'case-studies'
  resources :articles, only: %i[index show]
  resources :offices, only: %i[index show]
  resources :resources, only: %i[index show]
  # resources :videos, only: [:index, :show]
  resources :events, only: %i[index show]
  resources :pages, only: :show
  # FIXME: This is used in conjuction with the engine, so you end up with
  # /contacts/new and /contact-us/new - it should be one or the other.
  resources :contacts, only: %i[new create] # Here for legacy
  resources :contacts, only: %i[new create], path: 'contact-us' do
    post 'inpage-contact', on: :collection, as: :inpage, to: 'contacts#inpage'
  end
  resources :callback_requests, only: %i[new create], path: 'callback-request'

  %w[403 404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => '/admin'

  root to: 'homes#show'

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/testimonials',
      to: 'services#testimonials',
      as: :audience_child_service_testimonials

  get '/:audience_id/services/:parent_service_id/:service_id/:service_nested_id/frequently-asked-questions',
      to: 'services#frequently_asked_questions',
      as: :audience_child_service_frequently_asked_questions

  resources :audiences, only: :show, path: '', constraints: AudienceConstraint.new(Audience) do
    resources :services, only: :show do
      get 'testimonials'
      get 'frequently-asked-questions'

      resources :resources,
                only: :show,
                controller: 'services/resources'

      resources :service_pages,
                only: :show,
                path: 'pages',
                controller: 'services/pages'

      resources :services, only: :show, path: '', param: :nested_id do
        get 'testimonials'
        get 'frequently-asked-questions'

        resources :service_pages,
                  only: :show,
                  path: 'pages',
                  controller: 'services/pages'
      end
    end
  end

  resources :searches, only: :new

  get '/:audience_id/services/:parent_service_id/:service_id/:id',
      to: 'services#show',
      as: :audience_child_service

  get '/:audience_id/services/:grandparent_service_id/:parent_service_id/:service_id/pages/:id',
      to: 'services/pages#show',
      as: :audience_child_service_page

  # This has to be the last route in your list
  match '*path', to: 'errors#show', via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
Optimadmin::Engine.routes.draw do
  concern :imageable do
    member do
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  concern :orderable do
    collection do
      post 'order'
    end
  end

  concern :toggleable do
    member do
      get 'toggle'
    end
  end

  concern :publishable do |options|
    collection do
      resources :expired,
                as: "expired_#{options[:module]}",
                controller: "#{options[:module]}/expired"
      resources :scheduled,
                as: "scheduled_#{options[:module]}",
                controller: "#{options[:module]}/scheduled"
      resources :published,
                as: "published_#{options[:module]}",
                controller: "#{options[:module]}/published"
    end
  end

  # Module routes go below concerns

  get :resource_details, to: 'resources#details'
  resources :office_locations, concerns: %i[toggleable imageable]

  resources :resources do
    resources :resources_sections,
    except: :show,
    concerns: %i[orderable toggleable imageable],
    path: 'sections',
    controller: 'resources/sections'
  end

  namespace :conveyancing_quotes do
    resources :configurations,
              except: :show,
              concerns: %i[orderable toggleable imageable]
    resources :quote_locations do
      resources :users, only: %i[index show] do
        get 'incomplete', on: :collection
      end
    end
  end
end

app/views/resources/_resource.html.erb
<% cache [resource, resource.services.map(&:updated_at).max] do %>
  <div class="index-module index">
    <div class="standard-content-box standalone">
      <% present resource do |resource_presenter| %>
        <%= link_to (resource.services.present? && resource.services.first.audience.present? ? audience_service_resource_path(resource.services.first.audience, resource.services.first, resource) : resource.file.url) do %>
        <%#= link_to resource.file.url, title: resource_presenter.title, class: 'index-module-link', target: '_blank' do %>
          <%= content_tag :div, resource_presenter.show_image(alt: resource_presenter.title), class: 'index-module-image' if resource_presenter.index_image.present? %>
          <div class="index-module-details-overview">
            <div class="index-module-shares">
              <div class="social-share-count" href="<%= url_for([resource, only_path: false]) %>">
              </div>
            </div>
          </div>
          <div class="index-module-details-wrap">
            <div class="index-module-title">
              <%= resource_presenter.title %>
            </div>

            <div class="index-module-summary">
              <%= resource_presenter.summary %>
            </div>

            <%= content_tag :div,
              'Read More',
              {
                id: "Resource-#{ resource.id }",
                class: 'service-resource-download-button',
                title: resource_presenter.title
              } %>

            <%#= resource_presenter.linked_download(
              'Download',
              {
                id: "Resource-#{ resource.id }",
                class: 'service-resource-download-button',
                title: resource_presenter.title,
                target: '_blank',
              }) %>

        </div>
      <% end %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/resources/_resource_shelf.html.erb
<% present resource do |resource_presenter| %>
  <div class="helpful-guide helpful-guide-hover">
    <%= link_to audience_service_resource_path(resource.services.first.audience, resource.services.first, resource) do %>
    <%#= link_to resource.file.url, title: "Download #{resource_presenter.title}", target: '_blank' do %>
      <div class="helpful-guide-title">
        <%= resource_presenter.title %>
      </div>

      <%= content_tag :div, (resource_presenter.lazy_index_image(alt: '')), class: 'helpful-guide-image' if resource_presenter.index_image.present? %>

      <% present resource.services.first do |service_presenter| %>
        <%= content_tag :div, resource_presenter.summary, class: 'helpful-guide-content', style: service_presenter.colour_property_helper('background'),
          id: "Resource-#{ resource.id }" if resource.summary.present? %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/resources/index.html.erb
<%#= render 'resources/shared/index_header' %>

<%= content_for :head do %>
  <style>
    .index-module.index .standard-content-box.standalone {
      height: 100%;
    }
  </style>
<% end %>

<%= content_for :javascript do %>
  <%= javascript_include_tag 'https://npmcdn.com/masonry-layout@4.0/dist/masonry.pkgd.min.js' %>
  <script>
    $(window).load(function() {
      $('.index-module.index').matchHeight();
    });
  </script>
<% end %>

<div class="large-content">
  <aside class="large-content__aside">
    <div class="large-content-aside-sticky">
      <%= link_to 'Services',
                  '#large-content-aside-navigation',
                  class: 'slide-toggle
                          large-content-aside-navigation__toggle',
                  data: {
                    container: '.large-content-aside-navigation',
                    return: false
                  } %>


      <%= form_tag resources_path, method: :get do %>
        <div class="field">
          <%= select_tag :service_id, grouped_options_for_select(@audiences.order(:title).map{|x| [x.title, x.services.roots.displayed.order(:title).map{|y| [y.title, y.id] }]}, selected: params[:service_id]), prompt: 'Please select a service', class: 'submit-on-change' %>
        </div>
      <% end %>

      <% @audiences.each do |audience| %>
        <h2 class="large-content-aside-title__text">
          <%= audience.title %>
        </h2>


        <ul class="large-content-aside-navigation large-content-aside-navigation--without-icon" id="large-content-aside-navigation">
          <% audience.services.roots.where('services.id IN (?)', @service_ids).displayed.each do |service| %>
            <li class="large-content-aside-navigation__item">
              <%= link_to service.title, resources_path(service_id: service.id), class: "#{@service == service || (@service.present? && @service.root.present? && @service.root == service) ? 'active' : 'inactive'}" %>

              <% if @service == service || (@service.present? && @service.root.present? && @service.root == service) %>
                <ul class="large-content-aside-navigation large-content-aside-navigation--without-icon large-content-aside-navigation--nested" id="large-content-aside-navigation">
                  <% service.children.displayed.where('services.id IN (?)', @service_ids).each do |child| %>
                    <li class="large-content-aside-navigation__item">
                      <%= link_to child.title, resources_path(service_id: child.id), class: "#{@service == service ? 'active' : 'inactive'}" %>
                    </li>
                  <% end %>
                </ul>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </aside>

  <main class="large-content__main">
    <section class="large-content-element">
      <div class="large-content-element__container">
        <div class="large-content-inner">
          <div class="large-content-inner__main large-content-inner__main--full">
            <div class="large-content-masonry">
              <%= render partial: 'resources/resource',
                         collection: @resources,
                         as: :resource,
                         cached: true %>
            </div>

            <div class="module-pagination">
              <%= paginate @resources %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>